name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: 
      - github*
      # - master
  pull_request:
    branches: 
      - github* 

  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest] #, macos-latest] 

    steps:
      
      - name : Setup Environment Variables
        shell: python
        run: |
          import os
          from os import path
          main_dir = path.join(os.getcwd(),'..')
          main_dir = path.abspath(main_dir)
          print("::set-env name=_MAIN_DIR::{}".format(main_dir))
    
      - name: Cache build environment
        uses: actions/cache@v2
        env:
          cache-name: ${{ github.ref }}-${{ runner.os }}
        with:
          path: ${{ env._MAIN_DIR }}
          key: build-cache-${{ env.cache-name }}
            
      - uses: actions/checkout@v3
      
      - name: Build.py
        run: python build.py
          
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: Mineimator-release-${{ runner.os }}
          path: ${{ env._MAIN_DIR }}/build_release/bin/

    # For Release Upload
    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #    files: Mineimator-release-${{ runner.os }}.zip
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
